spring:
  application:
    name: dalidali-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dalidali?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8&amp&allowPublicKeyRetrieval=true&amp&&autoReconnect=true
    username: root
    password: root
  redis:
    password: root
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    publisher-returns: true
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
logging:
  level:
    root: ERROR
    pers.czj: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
server:
  port: 8083
