server:
  port: 8111
spring:
  application:
    name: dalidali-gateway
  redis:
  mvc:
    static-path-pattern: /*
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Methods
  routes:
    user-api:
      path: /userservice/**
      service-id: dalidali-user
      sensitive-headers: "*"
      custom-sensitive-headers: true
    video-api:
      path: /videoservice/**
      service-id: dalidali-video
      sensitive-headers: "*"
      custom-sensitive-headers: true
    comment-api:
      path: /commentservice/**
      service-id: dalidali-comment
      sensitive-headers: "*"
      custom-sensitive-headers: true
  sensitive-headers: "*"
  ignored-patterns:
    - /index.html

time:
  start: start_time