spring:
  application:
    name: dalidali-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dalidali?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8&amp&allowPublicKeyRetrieval=true&amp&&autoReconnect=true
    username: root
    password: root
  redis:
    password: chenzijia12300
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB
  mvc:
    static-path-pattern: /*
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:${apk.path-mapping}
server:
  port: 8183
logging:
  level:
    root: ERROR
    pers.czj: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 60000


apk:
  path-mapping: /apk/

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  url: http://192.168.99.103:9000/
  download-url: http://192.168.99.103:9000/
  bucket-name: dalidali-apk
