server:
  port: 8082

spring:
  application:
    name: dalidali-comment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dalidali?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8&amp&allowPublicKeyRetrieval=true&amp&&autoReconnect=true
    username: dalidali
    password: root
  redis:
    password: root
  jackson:
    serialization:
      write-dates-as-timestamps: true


eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.3:8100/eureka/
mybatis-plus:
  type-enums-package: pers.czj.constant
  global-config:
    db-config:
      logic-delete-field: table_name  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    pers.czj: INFO
    root: ERROR
  file:
    path: C:\Program Files\comment_log\

